name: Label issues
on:
  issues:
    types:
      - reopened
      - opened

jobs:
  check_author_team_membership:
    runs-on: ubuntu-latest
    steps:
      - name: Check if author is opsTrack member
        id: check_author
        run: |
          response=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              "https://api.github.com/orgs/${{ github.event.organization.login }}/teams/opsTrack/members")
          if echo "$response" | grep -q "\"login\": \"${{ github.event.issue.user.login }}\""; then
            echo "::set-output name=isMember::true"
          else
            echo "::set-output name=isMember::false"
          fi

  label_issues:
    needs: check_author_team_membership
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Label issues if opsTrack member
        if: steps.check_author_team_membership.outputs.isMember == 'true'
        run: |
          gh issue edit ${{ github.event.issue.number }} --add-label 2 codeowners reviews required
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
